package http

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"main/internal/usecase/createuser"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ICreateUserMock implements handler.iCreateUser
type ICreateUserMock struct {
	t minimock.Tester

	funcHandle          func(ctx context.Context, cmd createuser.Command) (err error)
	inspectFuncHandle   func(ctx context.Context, cmd createuser.Command)
	afterHandleCounter  uint64
	beforeHandleCounter uint64
	HandleMock          mICreateUserMockHandle
}

// NewICreateUserMock returns a mock for handler.iCreateUser
func NewICreateUserMock(t minimock.Tester) *ICreateUserMock {
	m := &ICreateUserMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.HandleMock = mICreateUserMockHandle{mock: m}
	m.HandleMock.callArgs = []*ICreateUserMockHandleParams{}

	return m
}

type mICreateUserMockHandle struct {
	mock               *ICreateUserMock
	defaultExpectation *ICreateUserMockHandleExpectation
	expectations       []*ICreateUserMockHandleExpectation

	callArgs []*ICreateUserMockHandleParams
	mutex    sync.RWMutex
}

// ICreateUserMockHandleExpectation specifies expectation struct of the iCreateUser.Handle
type ICreateUserMockHandleExpectation struct {
	mock    *ICreateUserMock
	params  *ICreateUserMockHandleParams
	results *ICreateUserMockHandleResults
	Counter uint64
}

// ICreateUserMockHandleParams contains parameters of the iCreateUser.Handle
type ICreateUserMockHandleParams struct {
	ctx context.Context
	cmd createuser.Command
}

// ICreateUserMockHandleResults contains results of the iCreateUser.Handle
type ICreateUserMockHandleResults struct {
	err error
}

// Expect sets up expected params for iCreateUser.Handle
func (mmHandle *mICreateUserMockHandle) Expect(ctx context.Context, cmd createuser.Command) *mICreateUserMockHandle {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("ICreateUserMock.Handle mock is already set by Set")
	}

	if mmHandle.defaultExpectation == nil {
		mmHandle.defaultExpectation = &ICreateUserMockHandleExpectation{}
	}

	mmHandle.defaultExpectation.params = &ICreateUserMockHandleParams{ctx, cmd}
	for _, e := range mmHandle.expectations {
		if minimock.Equal(e.params, mmHandle.defaultExpectation.params) {
			mmHandle.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHandle.defaultExpectation.params)
		}
	}

	return mmHandle
}

// Inspect accepts an inspector function that has same arguments as the iCreateUser.Handle
func (mmHandle *mICreateUserMockHandle) Inspect(f func(ctx context.Context, cmd createuser.Command)) *mICreateUserMockHandle {
	if mmHandle.mock.inspectFuncHandle != nil {
		mmHandle.mock.t.Fatalf("Inspect function is already set for ICreateUserMock.Handle")
	}

	mmHandle.mock.inspectFuncHandle = f

	return mmHandle
}

// Return sets up results that will be returned by iCreateUser.Handle
func (mmHandle *mICreateUserMockHandle) Return(err error) *ICreateUserMock {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("ICreateUserMock.Handle mock is already set by Set")
	}

	if mmHandle.defaultExpectation == nil {
		mmHandle.defaultExpectation = &ICreateUserMockHandleExpectation{mock: mmHandle.mock}
	}
	mmHandle.defaultExpectation.results = &ICreateUserMockHandleResults{err}
	return mmHandle.mock
}

// Set uses given function f to mock the iCreateUser.Handle method
func (mmHandle *mICreateUserMockHandle) Set(f func(ctx context.Context, cmd createuser.Command) (err error)) *ICreateUserMock {
	if mmHandle.defaultExpectation != nil {
		mmHandle.mock.t.Fatalf("Default expectation is already set for the iCreateUser.Handle method")
	}

	if len(mmHandle.expectations) > 0 {
		mmHandle.mock.t.Fatalf("Some expectations are already set for the iCreateUser.Handle method")
	}

	mmHandle.mock.funcHandle = f
	return mmHandle.mock
}

// When sets expectation for the iCreateUser.Handle which will trigger the result defined by the following
// Then helper
func (mmHandle *mICreateUserMockHandle) When(ctx context.Context, cmd createuser.Command) *ICreateUserMockHandleExpectation {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("ICreateUserMock.Handle mock is already set by Set")
	}

	expectation := &ICreateUserMockHandleExpectation{
		mock:   mmHandle.mock,
		params: &ICreateUserMockHandleParams{ctx, cmd},
	}
	mmHandle.expectations = append(mmHandle.expectations, expectation)
	return expectation
}

// Then sets up iCreateUser.Handle return parameters for the expectation previously defined by the When method
func (e *ICreateUserMockHandleExpectation) Then(err error) *ICreateUserMock {
	e.results = &ICreateUserMockHandleResults{err}
	return e.mock
}

// Handle implements handler.iCreateUser
func (mmHandle *ICreateUserMock) Handle(ctx context.Context, cmd createuser.Command) (err error) {
	mm_atomic.AddUint64(&mmHandle.beforeHandleCounter, 1)
	defer mm_atomic.AddUint64(&mmHandle.afterHandleCounter, 1)

	if mmHandle.inspectFuncHandle != nil {
		mmHandle.inspectFuncHandle(ctx, cmd)
	}

	mm_params := &ICreateUserMockHandleParams{ctx, cmd}

	// Record call args
	mmHandle.HandleMock.mutex.Lock()
	mmHandle.HandleMock.callArgs = append(mmHandle.HandleMock.callArgs, mm_params)
	mmHandle.HandleMock.mutex.Unlock()

	for _, e := range mmHandle.HandleMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmHandle.HandleMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHandle.HandleMock.defaultExpectation.Counter, 1)
		mm_want := mmHandle.HandleMock.defaultExpectation.params
		mm_got := ICreateUserMockHandleParams{ctx, cmd}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHandle.t.Errorf("ICreateUserMock.Handle got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHandle.HandleMock.defaultExpectation.results
		if mm_results == nil {
			mmHandle.t.Fatal("No results are set for the ICreateUserMock.Handle")
		}
		return (*mm_results).err
	}
	if mmHandle.funcHandle != nil {
		return mmHandle.funcHandle(ctx, cmd)
	}
	mmHandle.t.Fatalf("Unexpected call to ICreateUserMock.Handle. %v %v", ctx, cmd)
	return
}

// HandleAfterCounter returns a count of finished ICreateUserMock.Handle invocations
func (mmHandle *ICreateUserMock) HandleAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHandle.afterHandleCounter)
}

// HandleBeforeCounter returns a count of ICreateUserMock.Handle invocations
func (mmHandle *ICreateUserMock) HandleBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHandle.beforeHandleCounter)
}

// Calls returns a list of arguments used in each call to ICreateUserMock.Handle.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHandle *mICreateUserMockHandle) Calls() []*ICreateUserMockHandleParams {
	mmHandle.mutex.RLock()

	argCopy := make([]*ICreateUserMockHandleParams, len(mmHandle.callArgs))
	copy(argCopy, mmHandle.callArgs)

	mmHandle.mutex.RUnlock()

	return argCopy
}

// MinimockHandleDone returns true if the count of the Handle invocations corresponds
// the number of defined expectations
func (m *ICreateUserMock) MinimockHandleDone() bool {
	for _, e := range m.HandleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.HandleMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterHandleCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHandle != nil && mm_atomic.LoadUint64(&m.afterHandleCounter) < 1 {
		return false
	}
	return true
}

// MinimockHandleInspect logs each unmet expectation
func (m *ICreateUserMock) MinimockHandleInspect() {
	for _, e := range m.HandleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ICreateUserMock.Handle with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.HandleMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterHandleCounter) < 1 {
		if m.HandleMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ICreateUserMock.Handle")
		} else {
			m.t.Errorf("Expected call to ICreateUserMock.Handle with params: %#v", *m.HandleMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHandle != nil && mm_atomic.LoadUint64(&m.afterHandleCounter) < 1 {
		m.t.Error("Expected call to ICreateUserMock.Handle")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ICreateUserMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockHandleInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ICreateUserMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ICreateUserMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockHandleDone()
}
