// Code generated by http://github.com/gojuno/minimock (v3.3.11). DO NOT EDIT.

package http

import (
	"context"
	"main/internal/domain"
	"main/internal/usecase/getuserbyid"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// IGetUserMock implements handler.iGetUser
type IGetUserMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcHandle          func(ctx context.Context, q getuserbyid.Query) (up1 *domain.User, err error)
	inspectFuncHandle   func(ctx context.Context, q getuserbyid.Query)
	afterHandleCounter  uint64
	beforeHandleCounter uint64
	HandleMock          mIGetUserMockHandle
}

// NewIGetUserMock returns a mock for handler.iGetUser
func NewIGetUserMock(t minimock.Tester) *IGetUserMock {
	m := &IGetUserMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.HandleMock = mIGetUserMockHandle{mock: m}
	m.HandleMock.callArgs = []*IGetUserMockHandleParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIGetUserMockHandle struct {
	optional           bool
	mock               *IGetUserMock
	defaultExpectation *IGetUserMockHandleExpectation
	expectations       []*IGetUserMockHandleExpectation

	callArgs []*IGetUserMockHandleParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// IGetUserMockHandleExpectation specifies expectation struct of the iGetUser.Handle
type IGetUserMockHandleExpectation struct {
	mock      *IGetUserMock
	params    *IGetUserMockHandleParams
	paramPtrs *IGetUserMockHandleParamPtrs
	results   *IGetUserMockHandleResults
	Counter   uint64
}

// IGetUserMockHandleParams contains parameters of the iGetUser.Handle
type IGetUserMockHandleParams struct {
	ctx context.Context
	q   getuserbyid.Query
}

// IGetUserMockHandleParamPtrs contains pointers to parameters of the iGetUser.Handle
type IGetUserMockHandleParamPtrs struct {
	ctx *context.Context
	q   *getuserbyid.Query
}

// IGetUserMockHandleResults contains results of the iGetUser.Handle
type IGetUserMockHandleResults struct {
	up1 *domain.User
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHandle *mIGetUserMockHandle) Optional() *mIGetUserMockHandle {
	mmHandle.optional = true
	return mmHandle
}

// Expect sets up expected params for iGetUser.Handle
func (mmHandle *mIGetUserMockHandle) Expect(ctx context.Context, q getuserbyid.Query) *mIGetUserMockHandle {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by Set")
	}

	if mmHandle.defaultExpectation == nil {
		mmHandle.defaultExpectation = &IGetUserMockHandleExpectation{}
	}

	if mmHandle.defaultExpectation.paramPtrs != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by ExpectParams functions")
	}

	mmHandle.defaultExpectation.params = &IGetUserMockHandleParams{ctx, q}
	for _, e := range mmHandle.expectations {
		if minimock.Equal(e.params, mmHandle.defaultExpectation.params) {
			mmHandle.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHandle.defaultExpectation.params)
		}
	}

	return mmHandle
}

// ExpectCtxParam1 sets up expected param ctx for iGetUser.Handle
func (mmHandle *mIGetUserMockHandle) ExpectCtxParam1(ctx context.Context) *mIGetUserMockHandle {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by Set")
	}

	if mmHandle.defaultExpectation == nil {
		mmHandle.defaultExpectation = &IGetUserMockHandleExpectation{}
	}

	if mmHandle.defaultExpectation.params != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by Expect")
	}

	if mmHandle.defaultExpectation.paramPtrs == nil {
		mmHandle.defaultExpectation.paramPtrs = &IGetUserMockHandleParamPtrs{}
	}
	mmHandle.defaultExpectation.paramPtrs.ctx = &ctx

	return mmHandle
}

// ExpectQParam2 sets up expected param q for iGetUser.Handle
func (mmHandle *mIGetUserMockHandle) ExpectQParam2(q getuserbyid.Query) *mIGetUserMockHandle {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by Set")
	}

	if mmHandle.defaultExpectation == nil {
		mmHandle.defaultExpectation = &IGetUserMockHandleExpectation{}
	}

	if mmHandle.defaultExpectation.params != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by Expect")
	}

	if mmHandle.defaultExpectation.paramPtrs == nil {
		mmHandle.defaultExpectation.paramPtrs = &IGetUserMockHandleParamPtrs{}
	}
	mmHandle.defaultExpectation.paramPtrs.q = &q

	return mmHandle
}

// Inspect accepts an inspector function that has same arguments as the iGetUser.Handle
func (mmHandle *mIGetUserMockHandle) Inspect(f func(ctx context.Context, q getuserbyid.Query)) *mIGetUserMockHandle {
	if mmHandle.mock.inspectFuncHandle != nil {
		mmHandle.mock.t.Fatalf("Inspect function is already set for IGetUserMock.Handle")
	}

	mmHandle.mock.inspectFuncHandle = f

	return mmHandle
}

// Return sets up results that will be returned by iGetUser.Handle
func (mmHandle *mIGetUserMockHandle) Return(up1 *domain.User, err error) *IGetUserMock {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by Set")
	}

	if mmHandle.defaultExpectation == nil {
		mmHandle.defaultExpectation = &IGetUserMockHandleExpectation{mock: mmHandle.mock}
	}
	mmHandle.defaultExpectation.results = &IGetUserMockHandleResults{up1, err}
	return mmHandle.mock
}

// Set uses given function f to mock the iGetUser.Handle method
func (mmHandle *mIGetUserMockHandle) Set(f func(ctx context.Context, q getuserbyid.Query) (up1 *domain.User, err error)) *IGetUserMock {
	if mmHandle.defaultExpectation != nil {
		mmHandle.mock.t.Fatalf("Default expectation is already set for the iGetUser.Handle method")
	}

	if len(mmHandle.expectations) > 0 {
		mmHandle.mock.t.Fatalf("Some expectations are already set for the iGetUser.Handle method")
	}

	mmHandle.mock.funcHandle = f
	return mmHandle.mock
}

// When sets expectation for the iGetUser.Handle which will trigger the result defined by the following
// Then helper
func (mmHandle *mIGetUserMockHandle) When(ctx context.Context, q getuserbyid.Query) *IGetUserMockHandleExpectation {
	if mmHandle.mock.funcHandle != nil {
		mmHandle.mock.t.Fatalf("IGetUserMock.Handle mock is already set by Set")
	}

	expectation := &IGetUserMockHandleExpectation{
		mock:   mmHandle.mock,
		params: &IGetUserMockHandleParams{ctx, q},
	}
	mmHandle.expectations = append(mmHandle.expectations, expectation)
	return expectation
}

// Then sets up iGetUser.Handle return parameters for the expectation previously defined by the When method
func (e *IGetUserMockHandleExpectation) Then(up1 *domain.User, err error) *IGetUserMock {
	e.results = &IGetUserMockHandleResults{up1, err}
	return e.mock
}

// Times sets number of times iGetUser.Handle should be invoked
func (mmHandle *mIGetUserMockHandle) Times(n uint64) *mIGetUserMockHandle {
	if n == 0 {
		mmHandle.mock.t.Fatalf("Times of IGetUserMock.Handle mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHandle.expectedInvocations, n)
	return mmHandle
}

func (mmHandle *mIGetUserMockHandle) invocationsDone() bool {
	if len(mmHandle.expectations) == 0 && mmHandle.defaultExpectation == nil && mmHandle.mock.funcHandle == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHandle.mock.afterHandleCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHandle.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Handle implements handler.iGetUser
func (mmHandle *IGetUserMock) Handle(ctx context.Context, q getuserbyid.Query) (up1 *domain.User, err error) {
	mm_atomic.AddUint64(&mmHandle.beforeHandleCounter, 1)
	defer mm_atomic.AddUint64(&mmHandle.afterHandleCounter, 1)

	if mmHandle.inspectFuncHandle != nil {
		mmHandle.inspectFuncHandle(ctx, q)
	}

	mm_params := IGetUserMockHandleParams{ctx, q}

	// Record call args
	mmHandle.HandleMock.mutex.Lock()
	mmHandle.HandleMock.callArgs = append(mmHandle.HandleMock.callArgs, &mm_params)
	mmHandle.HandleMock.mutex.Unlock()

	for _, e := range mmHandle.HandleMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmHandle.HandleMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHandle.HandleMock.defaultExpectation.Counter, 1)
		mm_want := mmHandle.HandleMock.defaultExpectation.params
		mm_want_ptrs := mmHandle.HandleMock.defaultExpectation.paramPtrs

		mm_got := IGetUserMockHandleParams{ctx, q}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHandle.t.Errorf("IGetUserMock.Handle got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.q != nil && !minimock.Equal(*mm_want_ptrs.q, mm_got.q) {
				mmHandle.t.Errorf("IGetUserMock.Handle got unexpected parameter q, want: %#v, got: %#v%s\n", *mm_want_ptrs.q, mm_got.q, minimock.Diff(*mm_want_ptrs.q, mm_got.q))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHandle.t.Errorf("IGetUserMock.Handle got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHandle.HandleMock.defaultExpectation.results
		if mm_results == nil {
			mmHandle.t.Fatal("No results are set for the IGetUserMock.Handle")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmHandle.funcHandle != nil {
		return mmHandle.funcHandle(ctx, q)
	}
	mmHandle.t.Fatalf("Unexpected call to IGetUserMock.Handle. %v %v", ctx, q)
	return
}

// HandleAfterCounter returns a count of finished IGetUserMock.Handle invocations
func (mmHandle *IGetUserMock) HandleAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHandle.afterHandleCounter)
}

// HandleBeforeCounter returns a count of IGetUserMock.Handle invocations
func (mmHandle *IGetUserMock) HandleBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHandle.beforeHandleCounter)
}

// Calls returns a list of arguments used in each call to IGetUserMock.Handle.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHandle *mIGetUserMockHandle) Calls() []*IGetUserMockHandleParams {
	mmHandle.mutex.RLock()

	argCopy := make([]*IGetUserMockHandleParams, len(mmHandle.callArgs))
	copy(argCopy, mmHandle.callArgs)

	mmHandle.mutex.RUnlock()

	return argCopy
}

// MinimockHandleDone returns true if the count of the Handle invocations corresponds
// the number of defined expectations
func (m *IGetUserMock) MinimockHandleDone() bool {
	if m.HandleMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HandleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HandleMock.invocationsDone()
}

// MinimockHandleInspect logs each unmet expectation
func (m *IGetUserMock) MinimockHandleInspect() {
	for _, e := range m.HandleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IGetUserMock.Handle with params: %#v", *e.params)
		}
	}

	afterHandleCounter := mm_atomic.LoadUint64(&m.afterHandleCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HandleMock.defaultExpectation != nil && afterHandleCounter < 1 {
		if m.HandleMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IGetUserMock.Handle")
		} else {
			m.t.Errorf("Expected call to IGetUserMock.Handle with params: %#v", *m.HandleMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHandle != nil && afterHandleCounter < 1 {
		m.t.Error("Expected call to IGetUserMock.Handle")
	}

	if !m.HandleMock.invocationsDone() && afterHandleCounter > 0 {
		m.t.Errorf("Expected %d calls to IGetUserMock.Handle but found %d calls",
			mm_atomic.LoadUint64(&m.HandleMock.expectedInvocations), afterHandleCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IGetUserMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockHandleInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IGetUserMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IGetUserMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockHandleDone()
}
