// Code generated by http://github.com/gojuno/minimock (v3.3.11). DO NOT EDIT.

package eventrouter

import (
	"context"
	"main/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// IUserEventRepoMock implements eventrouter.iUserEventRepo
type IUserEventRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSendUserCreatedEvent          func(ctx context.Context, event domain.UserCreatedEvent) (err error)
	inspectFuncSendUserCreatedEvent   func(ctx context.Context, event domain.UserCreatedEvent)
	afterSendUserCreatedEventCounter  uint64
	beforeSendUserCreatedEventCounter uint64
	SendUserCreatedEventMock          mIUserEventRepoMockSendUserCreatedEvent
}

// NewIUserEventRepoMock returns a mock for eventrouter.iUserEventRepo
func NewIUserEventRepoMock(t minimock.Tester) *IUserEventRepoMock {
	m := &IUserEventRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendUserCreatedEventMock = mIUserEventRepoMockSendUserCreatedEvent{mock: m}
	m.SendUserCreatedEventMock.callArgs = []*IUserEventRepoMockSendUserCreatedEventParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIUserEventRepoMockSendUserCreatedEvent struct {
	optional           bool
	mock               *IUserEventRepoMock
	defaultExpectation *IUserEventRepoMockSendUserCreatedEventExpectation
	expectations       []*IUserEventRepoMockSendUserCreatedEventExpectation

	callArgs []*IUserEventRepoMockSendUserCreatedEventParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// IUserEventRepoMockSendUserCreatedEventExpectation specifies expectation struct of the iUserEventRepo.SendUserCreatedEvent
type IUserEventRepoMockSendUserCreatedEventExpectation struct {
	mock      *IUserEventRepoMock
	params    *IUserEventRepoMockSendUserCreatedEventParams
	paramPtrs *IUserEventRepoMockSendUserCreatedEventParamPtrs
	results   *IUserEventRepoMockSendUserCreatedEventResults
	Counter   uint64
}

// IUserEventRepoMockSendUserCreatedEventParams contains parameters of the iUserEventRepo.SendUserCreatedEvent
type IUserEventRepoMockSendUserCreatedEventParams struct {
	ctx   context.Context
	event domain.UserCreatedEvent
}

// IUserEventRepoMockSendUserCreatedEventParamPtrs contains pointers to parameters of the iUserEventRepo.SendUserCreatedEvent
type IUserEventRepoMockSendUserCreatedEventParamPtrs struct {
	ctx   *context.Context
	event *domain.UserCreatedEvent
}

// IUserEventRepoMockSendUserCreatedEventResults contains results of the iUserEventRepo.SendUserCreatedEvent
type IUserEventRepoMockSendUserCreatedEventResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) Optional() *mIUserEventRepoMockSendUserCreatedEvent {
	mmSendUserCreatedEvent.optional = true
	return mmSendUserCreatedEvent
}

// Expect sets up expected params for iUserEventRepo.SendUserCreatedEvent
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) Expect(ctx context.Context, event domain.UserCreatedEvent) *mIUserEventRepoMockSendUserCreatedEvent {
	if mmSendUserCreatedEvent.mock.funcSendUserCreatedEvent != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by Set")
	}

	if mmSendUserCreatedEvent.defaultExpectation == nil {
		mmSendUserCreatedEvent.defaultExpectation = &IUserEventRepoMockSendUserCreatedEventExpectation{}
	}

	if mmSendUserCreatedEvent.defaultExpectation.paramPtrs != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by ExpectParams functions")
	}

	mmSendUserCreatedEvent.defaultExpectation.params = &IUserEventRepoMockSendUserCreatedEventParams{ctx, event}
	for _, e := range mmSendUserCreatedEvent.expectations {
		if minimock.Equal(e.params, mmSendUserCreatedEvent.defaultExpectation.params) {
			mmSendUserCreatedEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendUserCreatedEvent.defaultExpectation.params)
		}
	}

	return mmSendUserCreatedEvent
}

// ExpectCtxParam1 sets up expected param ctx for iUserEventRepo.SendUserCreatedEvent
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) ExpectCtxParam1(ctx context.Context) *mIUserEventRepoMockSendUserCreatedEvent {
	if mmSendUserCreatedEvent.mock.funcSendUserCreatedEvent != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by Set")
	}

	if mmSendUserCreatedEvent.defaultExpectation == nil {
		mmSendUserCreatedEvent.defaultExpectation = &IUserEventRepoMockSendUserCreatedEventExpectation{}
	}

	if mmSendUserCreatedEvent.defaultExpectation.params != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by Expect")
	}

	if mmSendUserCreatedEvent.defaultExpectation.paramPtrs == nil {
		mmSendUserCreatedEvent.defaultExpectation.paramPtrs = &IUserEventRepoMockSendUserCreatedEventParamPtrs{}
	}
	mmSendUserCreatedEvent.defaultExpectation.paramPtrs.ctx = &ctx

	return mmSendUserCreatedEvent
}

// ExpectEventParam2 sets up expected param event for iUserEventRepo.SendUserCreatedEvent
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) ExpectEventParam2(event domain.UserCreatedEvent) *mIUserEventRepoMockSendUserCreatedEvent {
	if mmSendUserCreatedEvent.mock.funcSendUserCreatedEvent != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by Set")
	}

	if mmSendUserCreatedEvent.defaultExpectation == nil {
		mmSendUserCreatedEvent.defaultExpectation = &IUserEventRepoMockSendUserCreatedEventExpectation{}
	}

	if mmSendUserCreatedEvent.defaultExpectation.params != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by Expect")
	}

	if mmSendUserCreatedEvent.defaultExpectation.paramPtrs == nil {
		mmSendUserCreatedEvent.defaultExpectation.paramPtrs = &IUserEventRepoMockSendUserCreatedEventParamPtrs{}
	}
	mmSendUserCreatedEvent.defaultExpectation.paramPtrs.event = &event

	return mmSendUserCreatedEvent
}

// Inspect accepts an inspector function that has same arguments as the iUserEventRepo.SendUserCreatedEvent
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) Inspect(f func(ctx context.Context, event domain.UserCreatedEvent)) *mIUserEventRepoMockSendUserCreatedEvent {
	if mmSendUserCreatedEvent.mock.inspectFuncSendUserCreatedEvent != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("Inspect function is already set for IUserEventRepoMock.SendUserCreatedEvent")
	}

	mmSendUserCreatedEvent.mock.inspectFuncSendUserCreatedEvent = f

	return mmSendUserCreatedEvent
}

// Return sets up results that will be returned by iUserEventRepo.SendUserCreatedEvent
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) Return(err error) *IUserEventRepoMock {
	if mmSendUserCreatedEvent.mock.funcSendUserCreatedEvent != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by Set")
	}

	if mmSendUserCreatedEvent.defaultExpectation == nil {
		mmSendUserCreatedEvent.defaultExpectation = &IUserEventRepoMockSendUserCreatedEventExpectation{mock: mmSendUserCreatedEvent.mock}
	}
	mmSendUserCreatedEvent.defaultExpectation.results = &IUserEventRepoMockSendUserCreatedEventResults{err}
	return mmSendUserCreatedEvent.mock
}

// Set uses given function f to mock the iUserEventRepo.SendUserCreatedEvent method
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) Set(f func(ctx context.Context, event domain.UserCreatedEvent) (err error)) *IUserEventRepoMock {
	if mmSendUserCreatedEvent.defaultExpectation != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("Default expectation is already set for the iUserEventRepo.SendUserCreatedEvent method")
	}

	if len(mmSendUserCreatedEvent.expectations) > 0 {
		mmSendUserCreatedEvent.mock.t.Fatalf("Some expectations are already set for the iUserEventRepo.SendUserCreatedEvent method")
	}

	mmSendUserCreatedEvent.mock.funcSendUserCreatedEvent = f
	return mmSendUserCreatedEvent.mock
}

// When sets expectation for the iUserEventRepo.SendUserCreatedEvent which will trigger the result defined by the following
// Then helper
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) When(ctx context.Context, event domain.UserCreatedEvent) *IUserEventRepoMockSendUserCreatedEventExpectation {
	if mmSendUserCreatedEvent.mock.funcSendUserCreatedEvent != nil {
		mmSendUserCreatedEvent.mock.t.Fatalf("IUserEventRepoMock.SendUserCreatedEvent mock is already set by Set")
	}

	expectation := &IUserEventRepoMockSendUserCreatedEventExpectation{
		mock:   mmSendUserCreatedEvent.mock,
		params: &IUserEventRepoMockSendUserCreatedEventParams{ctx, event},
	}
	mmSendUserCreatedEvent.expectations = append(mmSendUserCreatedEvent.expectations, expectation)
	return expectation
}

// Then sets up iUserEventRepo.SendUserCreatedEvent return parameters for the expectation previously defined by the When method
func (e *IUserEventRepoMockSendUserCreatedEventExpectation) Then(err error) *IUserEventRepoMock {
	e.results = &IUserEventRepoMockSendUserCreatedEventResults{err}
	return e.mock
}

// Times sets number of times iUserEventRepo.SendUserCreatedEvent should be invoked
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) Times(n uint64) *mIUserEventRepoMockSendUserCreatedEvent {
	if n == 0 {
		mmSendUserCreatedEvent.mock.t.Fatalf("Times of IUserEventRepoMock.SendUserCreatedEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendUserCreatedEvent.expectedInvocations, n)
	return mmSendUserCreatedEvent
}

func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) invocationsDone() bool {
	if len(mmSendUserCreatedEvent.expectations) == 0 && mmSendUserCreatedEvent.defaultExpectation == nil && mmSendUserCreatedEvent.mock.funcSendUserCreatedEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendUserCreatedEvent.mock.afterSendUserCreatedEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendUserCreatedEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendUserCreatedEvent implements eventrouter.iUserEventRepo
func (mmSendUserCreatedEvent *IUserEventRepoMock) SendUserCreatedEvent(ctx context.Context, event domain.UserCreatedEvent) (err error) {
	mm_atomic.AddUint64(&mmSendUserCreatedEvent.beforeSendUserCreatedEventCounter, 1)
	defer mm_atomic.AddUint64(&mmSendUserCreatedEvent.afterSendUserCreatedEventCounter, 1)

	if mmSendUserCreatedEvent.inspectFuncSendUserCreatedEvent != nil {
		mmSendUserCreatedEvent.inspectFuncSendUserCreatedEvent(ctx, event)
	}

	mm_params := IUserEventRepoMockSendUserCreatedEventParams{ctx, event}

	// Record call args
	mmSendUserCreatedEvent.SendUserCreatedEventMock.mutex.Lock()
	mmSendUserCreatedEvent.SendUserCreatedEventMock.callArgs = append(mmSendUserCreatedEvent.SendUserCreatedEventMock.callArgs, &mm_params)
	mmSendUserCreatedEvent.SendUserCreatedEventMock.mutex.Unlock()

	for _, e := range mmSendUserCreatedEvent.SendUserCreatedEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendUserCreatedEvent.SendUserCreatedEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendUserCreatedEvent.SendUserCreatedEventMock.defaultExpectation.Counter, 1)
		mm_want := mmSendUserCreatedEvent.SendUserCreatedEventMock.defaultExpectation.params
		mm_want_ptrs := mmSendUserCreatedEvent.SendUserCreatedEventMock.defaultExpectation.paramPtrs

		mm_got := IUserEventRepoMockSendUserCreatedEventParams{ctx, event}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendUserCreatedEvent.t.Errorf("IUserEventRepoMock.SendUserCreatedEvent got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.event != nil && !minimock.Equal(*mm_want_ptrs.event, mm_got.event) {
				mmSendUserCreatedEvent.t.Errorf("IUserEventRepoMock.SendUserCreatedEvent got unexpected parameter event, want: %#v, got: %#v%s\n", *mm_want_ptrs.event, mm_got.event, minimock.Diff(*mm_want_ptrs.event, mm_got.event))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendUserCreatedEvent.t.Errorf("IUserEventRepoMock.SendUserCreatedEvent got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendUserCreatedEvent.SendUserCreatedEventMock.defaultExpectation.results
		if mm_results == nil {
			mmSendUserCreatedEvent.t.Fatal("No results are set for the IUserEventRepoMock.SendUserCreatedEvent")
		}
		return (*mm_results).err
	}
	if mmSendUserCreatedEvent.funcSendUserCreatedEvent != nil {
		return mmSendUserCreatedEvent.funcSendUserCreatedEvent(ctx, event)
	}
	mmSendUserCreatedEvent.t.Fatalf("Unexpected call to IUserEventRepoMock.SendUserCreatedEvent. %v %v", ctx, event)
	return
}

// SendUserCreatedEventAfterCounter returns a count of finished IUserEventRepoMock.SendUserCreatedEvent invocations
func (mmSendUserCreatedEvent *IUserEventRepoMock) SendUserCreatedEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendUserCreatedEvent.afterSendUserCreatedEventCounter)
}

// SendUserCreatedEventBeforeCounter returns a count of IUserEventRepoMock.SendUserCreatedEvent invocations
func (mmSendUserCreatedEvent *IUserEventRepoMock) SendUserCreatedEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendUserCreatedEvent.beforeSendUserCreatedEventCounter)
}

// Calls returns a list of arguments used in each call to IUserEventRepoMock.SendUserCreatedEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendUserCreatedEvent *mIUserEventRepoMockSendUserCreatedEvent) Calls() []*IUserEventRepoMockSendUserCreatedEventParams {
	mmSendUserCreatedEvent.mutex.RLock()

	argCopy := make([]*IUserEventRepoMockSendUserCreatedEventParams, len(mmSendUserCreatedEvent.callArgs))
	copy(argCopy, mmSendUserCreatedEvent.callArgs)

	mmSendUserCreatedEvent.mutex.RUnlock()

	return argCopy
}

// MinimockSendUserCreatedEventDone returns true if the count of the SendUserCreatedEvent invocations corresponds
// the number of defined expectations
func (m *IUserEventRepoMock) MinimockSendUserCreatedEventDone() bool {
	if m.SendUserCreatedEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendUserCreatedEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendUserCreatedEventMock.invocationsDone()
}

// MinimockSendUserCreatedEventInspect logs each unmet expectation
func (m *IUserEventRepoMock) MinimockSendUserCreatedEventInspect() {
	for _, e := range m.SendUserCreatedEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IUserEventRepoMock.SendUserCreatedEvent with params: %#v", *e.params)
		}
	}

	afterSendUserCreatedEventCounter := mm_atomic.LoadUint64(&m.afterSendUserCreatedEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendUserCreatedEventMock.defaultExpectation != nil && afterSendUserCreatedEventCounter < 1 {
		if m.SendUserCreatedEventMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IUserEventRepoMock.SendUserCreatedEvent")
		} else {
			m.t.Errorf("Expected call to IUserEventRepoMock.SendUserCreatedEvent with params: %#v", *m.SendUserCreatedEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendUserCreatedEvent != nil && afterSendUserCreatedEventCounter < 1 {
		m.t.Error("Expected call to IUserEventRepoMock.SendUserCreatedEvent")
	}

	if !m.SendUserCreatedEventMock.invocationsDone() && afterSendUserCreatedEventCounter > 0 {
		m.t.Errorf("Expected %d calls to IUserEventRepoMock.SendUserCreatedEvent but found %d calls",
			mm_atomic.LoadUint64(&m.SendUserCreatedEventMock.expectedInvocations), afterSendUserCreatedEventCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IUserEventRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendUserCreatedEventInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IUserEventRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IUserEventRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendUserCreatedEventDone()
}
