// Code generated by http://github.com/gojuno/minimock (v3.3.11). DO NOT EDIT.

package activateHabit

import (
	"main/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// IUserRepoMock implements activatehabit.iUserRepo
type IUserRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcActivateHabit          func(userID uuid.UUID, habitID uuid.UUID) (err error)
	inspectFuncActivateHabit   func(userID uuid.UUID, habitID uuid.UUID)
	afterActivateHabitCounter  uint64
	beforeActivateHabitCounter uint64
	ActivateHabitMock          mIUserRepoMockActivateHabit

	funcGetUserByID          func(userID uuid.UUID) (up1 *domain.User, err error)
	inspectFuncGetUserByID   func(userID uuid.UUID)
	afterGetUserByIDCounter  uint64
	beforeGetUserByIDCounter uint64
	GetUserByIDMock          mIUserRepoMockGetUserByID
}

// NewIUserRepoMock returns a mock for activatehabit.iUserRepo
func NewIUserRepoMock(t minimock.Tester) *IUserRepoMock {
	m := &IUserRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ActivateHabitMock = mIUserRepoMockActivateHabit{mock: m}
	m.ActivateHabitMock.callArgs = []*IUserRepoMockActivateHabitParams{}

	m.GetUserByIDMock = mIUserRepoMockGetUserByID{mock: m}
	m.GetUserByIDMock.callArgs = []*IUserRepoMockGetUserByIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIUserRepoMockActivateHabit struct {
	optional           bool
	mock               *IUserRepoMock
	defaultExpectation *IUserRepoMockActivateHabitExpectation
	expectations       []*IUserRepoMockActivateHabitExpectation

	callArgs []*IUserRepoMockActivateHabitParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// IUserRepoMockActivateHabitExpectation specifies expectation struct of the iUserRepo.ActivateHabit
type IUserRepoMockActivateHabitExpectation struct {
	mock      *IUserRepoMock
	params    *IUserRepoMockActivateHabitParams
	paramPtrs *IUserRepoMockActivateHabitParamPtrs
	results   *IUserRepoMockActivateHabitResults
	Counter   uint64
}

// IUserRepoMockActivateHabitParams contains parameters of the iUserRepo.ActivateHabit
type IUserRepoMockActivateHabitParams struct {
	userID  uuid.UUID
	habitID uuid.UUID
}

// IUserRepoMockActivateHabitParamPtrs contains pointers to parameters of the iUserRepo.ActivateHabit
type IUserRepoMockActivateHabitParamPtrs struct {
	userID  *uuid.UUID
	habitID *uuid.UUID
}

// IUserRepoMockActivateHabitResults contains results of the iUserRepo.ActivateHabit
type IUserRepoMockActivateHabitResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmActivateHabit *mIUserRepoMockActivateHabit) Optional() *mIUserRepoMockActivateHabit {
	mmActivateHabit.optional = true
	return mmActivateHabit
}

// Expect sets up expected params for iUserRepo.ActivateHabit
func (mmActivateHabit *mIUserRepoMockActivateHabit) Expect(userID uuid.UUID, habitID uuid.UUID) *mIUserRepoMockActivateHabit {
	if mmActivateHabit.mock.funcActivateHabit != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by Set")
	}

	if mmActivateHabit.defaultExpectation == nil {
		mmActivateHabit.defaultExpectation = &IUserRepoMockActivateHabitExpectation{}
	}

	if mmActivateHabit.defaultExpectation.paramPtrs != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by ExpectParams functions")
	}

	mmActivateHabit.defaultExpectation.params = &IUserRepoMockActivateHabitParams{userID, habitID}
	for _, e := range mmActivateHabit.expectations {
		if minimock.Equal(e.params, mmActivateHabit.defaultExpectation.params) {
			mmActivateHabit.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmActivateHabit.defaultExpectation.params)
		}
	}

	return mmActivateHabit
}

// ExpectUserIDParam1 sets up expected param userID for iUserRepo.ActivateHabit
func (mmActivateHabit *mIUserRepoMockActivateHabit) ExpectUserIDParam1(userID uuid.UUID) *mIUserRepoMockActivateHabit {
	if mmActivateHabit.mock.funcActivateHabit != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by Set")
	}

	if mmActivateHabit.defaultExpectation == nil {
		mmActivateHabit.defaultExpectation = &IUserRepoMockActivateHabitExpectation{}
	}

	if mmActivateHabit.defaultExpectation.params != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by Expect")
	}

	if mmActivateHabit.defaultExpectation.paramPtrs == nil {
		mmActivateHabit.defaultExpectation.paramPtrs = &IUserRepoMockActivateHabitParamPtrs{}
	}
	mmActivateHabit.defaultExpectation.paramPtrs.userID = &userID

	return mmActivateHabit
}

// ExpectHabitIDParam2 sets up expected param habitID for iUserRepo.ActivateHabit
func (mmActivateHabit *mIUserRepoMockActivateHabit) ExpectHabitIDParam2(habitID uuid.UUID) *mIUserRepoMockActivateHabit {
	if mmActivateHabit.mock.funcActivateHabit != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by Set")
	}

	if mmActivateHabit.defaultExpectation == nil {
		mmActivateHabit.defaultExpectation = &IUserRepoMockActivateHabitExpectation{}
	}

	if mmActivateHabit.defaultExpectation.params != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by Expect")
	}

	if mmActivateHabit.defaultExpectation.paramPtrs == nil {
		mmActivateHabit.defaultExpectation.paramPtrs = &IUserRepoMockActivateHabitParamPtrs{}
	}
	mmActivateHabit.defaultExpectation.paramPtrs.habitID = &habitID

	return mmActivateHabit
}

// Inspect accepts an inspector function that has same arguments as the iUserRepo.ActivateHabit
func (mmActivateHabit *mIUserRepoMockActivateHabit) Inspect(f func(userID uuid.UUID, habitID uuid.UUID)) *mIUserRepoMockActivateHabit {
	if mmActivateHabit.mock.inspectFuncActivateHabit != nil {
		mmActivateHabit.mock.t.Fatalf("Inspect function is already set for IUserRepoMock.ActivateHabit")
	}

	mmActivateHabit.mock.inspectFuncActivateHabit = f

	return mmActivateHabit
}

// Return sets up results that will be returned by iUserRepo.ActivateHabit
func (mmActivateHabit *mIUserRepoMockActivateHabit) Return(err error) *IUserRepoMock {
	if mmActivateHabit.mock.funcActivateHabit != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by Set")
	}

	if mmActivateHabit.defaultExpectation == nil {
		mmActivateHabit.defaultExpectation = &IUserRepoMockActivateHabitExpectation{mock: mmActivateHabit.mock}
	}
	mmActivateHabit.defaultExpectation.results = &IUserRepoMockActivateHabitResults{err}
	return mmActivateHabit.mock
}

// Set uses given function f to mock the iUserRepo.ActivateHabit method
func (mmActivateHabit *mIUserRepoMockActivateHabit) Set(f func(userID uuid.UUID, habitID uuid.UUID) (err error)) *IUserRepoMock {
	if mmActivateHabit.defaultExpectation != nil {
		mmActivateHabit.mock.t.Fatalf("Default expectation is already set for the iUserRepo.ActivateHabit method")
	}

	if len(mmActivateHabit.expectations) > 0 {
		mmActivateHabit.mock.t.Fatalf("Some expectations are already set for the iUserRepo.ActivateHabit method")
	}

	mmActivateHabit.mock.funcActivateHabit = f
	return mmActivateHabit.mock
}

// When sets expectation for the iUserRepo.ActivateHabit which will trigger the result defined by the following
// Then helper
func (mmActivateHabit *mIUserRepoMockActivateHabit) When(userID uuid.UUID, habitID uuid.UUID) *IUserRepoMockActivateHabitExpectation {
	if mmActivateHabit.mock.funcActivateHabit != nil {
		mmActivateHabit.mock.t.Fatalf("IUserRepoMock.ActivateHabit mock is already set by Set")
	}

	expectation := &IUserRepoMockActivateHabitExpectation{
		mock:   mmActivateHabit.mock,
		params: &IUserRepoMockActivateHabitParams{userID, habitID},
	}
	mmActivateHabit.expectations = append(mmActivateHabit.expectations, expectation)
	return expectation
}

// Then sets up iUserRepo.ActivateHabit return parameters for the expectation previously defined by the When method
func (e *IUserRepoMockActivateHabitExpectation) Then(err error) *IUserRepoMock {
	e.results = &IUserRepoMockActivateHabitResults{err}
	return e.mock
}

// Times sets number of times iUserRepo.ActivateHabit should be invoked
func (mmActivateHabit *mIUserRepoMockActivateHabit) Times(n uint64) *mIUserRepoMockActivateHabit {
	if n == 0 {
		mmActivateHabit.mock.t.Fatalf("Times of IUserRepoMock.ActivateHabit mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmActivateHabit.expectedInvocations, n)
	return mmActivateHabit
}

func (mmActivateHabit *mIUserRepoMockActivateHabit) invocationsDone() bool {
	if len(mmActivateHabit.expectations) == 0 && mmActivateHabit.defaultExpectation == nil && mmActivateHabit.mock.funcActivateHabit == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmActivateHabit.mock.afterActivateHabitCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmActivateHabit.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ActivateHabit implements activatehabit.iUserRepo
func (mmActivateHabit *IUserRepoMock) ActivateHabit(userID uuid.UUID, habitID uuid.UUID) (err error) {
	mm_atomic.AddUint64(&mmActivateHabit.beforeActivateHabitCounter, 1)
	defer mm_atomic.AddUint64(&mmActivateHabit.afterActivateHabitCounter, 1)

	if mmActivateHabit.inspectFuncActivateHabit != nil {
		mmActivateHabit.inspectFuncActivateHabit(userID, habitID)
	}

	mm_params := IUserRepoMockActivateHabitParams{userID, habitID}

	// Record call args
	mmActivateHabit.ActivateHabitMock.mutex.Lock()
	mmActivateHabit.ActivateHabitMock.callArgs = append(mmActivateHabit.ActivateHabitMock.callArgs, &mm_params)
	mmActivateHabit.ActivateHabitMock.mutex.Unlock()

	for _, e := range mmActivateHabit.ActivateHabitMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmActivateHabit.ActivateHabitMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmActivateHabit.ActivateHabitMock.defaultExpectation.Counter, 1)
		mm_want := mmActivateHabit.ActivateHabitMock.defaultExpectation.params
		mm_want_ptrs := mmActivateHabit.ActivateHabitMock.defaultExpectation.paramPtrs

		mm_got := IUserRepoMockActivateHabitParams{userID, habitID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmActivateHabit.t.Errorf("IUserRepoMock.ActivateHabit got unexpected parameter userID, want: %#v, got: %#v%s\n", *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.habitID != nil && !minimock.Equal(*mm_want_ptrs.habitID, mm_got.habitID) {
				mmActivateHabit.t.Errorf("IUserRepoMock.ActivateHabit got unexpected parameter habitID, want: %#v, got: %#v%s\n", *mm_want_ptrs.habitID, mm_got.habitID, minimock.Diff(*mm_want_ptrs.habitID, mm_got.habitID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmActivateHabit.t.Errorf("IUserRepoMock.ActivateHabit got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmActivateHabit.ActivateHabitMock.defaultExpectation.results
		if mm_results == nil {
			mmActivateHabit.t.Fatal("No results are set for the IUserRepoMock.ActivateHabit")
		}
		return (*mm_results).err
	}
	if mmActivateHabit.funcActivateHabit != nil {
		return mmActivateHabit.funcActivateHabit(userID, habitID)
	}
	mmActivateHabit.t.Fatalf("Unexpected call to IUserRepoMock.ActivateHabit. %v %v", userID, habitID)
	return
}

// ActivateHabitAfterCounter returns a count of finished IUserRepoMock.ActivateHabit invocations
func (mmActivateHabit *IUserRepoMock) ActivateHabitAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmActivateHabit.afterActivateHabitCounter)
}

// ActivateHabitBeforeCounter returns a count of IUserRepoMock.ActivateHabit invocations
func (mmActivateHabit *IUserRepoMock) ActivateHabitBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmActivateHabit.beforeActivateHabitCounter)
}

// Calls returns a list of arguments used in each call to IUserRepoMock.ActivateHabit.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmActivateHabit *mIUserRepoMockActivateHabit) Calls() []*IUserRepoMockActivateHabitParams {
	mmActivateHabit.mutex.RLock()

	argCopy := make([]*IUserRepoMockActivateHabitParams, len(mmActivateHabit.callArgs))
	copy(argCopy, mmActivateHabit.callArgs)

	mmActivateHabit.mutex.RUnlock()

	return argCopy
}

// MinimockActivateHabitDone returns true if the count of the ActivateHabit invocations corresponds
// the number of defined expectations
func (m *IUserRepoMock) MinimockActivateHabitDone() bool {
	if m.ActivateHabitMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ActivateHabitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ActivateHabitMock.invocationsDone()
}

// MinimockActivateHabitInspect logs each unmet expectation
func (m *IUserRepoMock) MinimockActivateHabitInspect() {
	for _, e := range m.ActivateHabitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IUserRepoMock.ActivateHabit with params: %#v", *e.params)
		}
	}

	afterActivateHabitCounter := mm_atomic.LoadUint64(&m.afterActivateHabitCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ActivateHabitMock.defaultExpectation != nil && afterActivateHabitCounter < 1 {
		if m.ActivateHabitMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IUserRepoMock.ActivateHabit")
		} else {
			m.t.Errorf("Expected call to IUserRepoMock.ActivateHabit with params: %#v", *m.ActivateHabitMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcActivateHabit != nil && afterActivateHabitCounter < 1 {
		m.t.Error("Expected call to IUserRepoMock.ActivateHabit")
	}

	if !m.ActivateHabitMock.invocationsDone() && afterActivateHabitCounter > 0 {
		m.t.Errorf("Expected %d calls to IUserRepoMock.ActivateHabit but found %d calls",
			mm_atomic.LoadUint64(&m.ActivateHabitMock.expectedInvocations), afterActivateHabitCounter)
	}
}

type mIUserRepoMockGetUserByID struct {
	optional           bool
	mock               *IUserRepoMock
	defaultExpectation *IUserRepoMockGetUserByIDExpectation
	expectations       []*IUserRepoMockGetUserByIDExpectation

	callArgs []*IUserRepoMockGetUserByIDParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// IUserRepoMockGetUserByIDExpectation specifies expectation struct of the iUserRepo.GetUserByID
type IUserRepoMockGetUserByIDExpectation struct {
	mock      *IUserRepoMock
	params    *IUserRepoMockGetUserByIDParams
	paramPtrs *IUserRepoMockGetUserByIDParamPtrs
	results   *IUserRepoMockGetUserByIDResults
	Counter   uint64
}

// IUserRepoMockGetUserByIDParams contains parameters of the iUserRepo.GetUserByID
type IUserRepoMockGetUserByIDParams struct {
	userID uuid.UUID
}

// IUserRepoMockGetUserByIDParamPtrs contains pointers to parameters of the iUserRepo.GetUserByID
type IUserRepoMockGetUserByIDParamPtrs struct {
	userID *uuid.UUID
}

// IUserRepoMockGetUserByIDResults contains results of the iUserRepo.GetUserByID
type IUserRepoMockGetUserByIDResults struct {
	up1 *domain.User
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserByID *mIUserRepoMockGetUserByID) Optional() *mIUserRepoMockGetUserByID {
	mmGetUserByID.optional = true
	return mmGetUserByID
}

// Expect sets up expected params for iUserRepo.GetUserByID
func (mmGetUserByID *mIUserRepoMockGetUserByID) Expect(userID uuid.UUID) *mIUserRepoMockGetUserByID {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("IUserRepoMock.GetUserByID mock is already set by Set")
	}

	if mmGetUserByID.defaultExpectation == nil {
		mmGetUserByID.defaultExpectation = &IUserRepoMockGetUserByIDExpectation{}
	}

	if mmGetUserByID.defaultExpectation.paramPtrs != nil {
		mmGetUserByID.mock.t.Fatalf("IUserRepoMock.GetUserByID mock is already set by ExpectParams functions")
	}

	mmGetUserByID.defaultExpectation.params = &IUserRepoMockGetUserByIDParams{userID}
	for _, e := range mmGetUserByID.expectations {
		if minimock.Equal(e.params, mmGetUserByID.defaultExpectation.params) {
			mmGetUserByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserByID.defaultExpectation.params)
		}
	}

	return mmGetUserByID
}

// ExpectUserIDParam1 sets up expected param userID for iUserRepo.GetUserByID
func (mmGetUserByID *mIUserRepoMockGetUserByID) ExpectUserIDParam1(userID uuid.UUID) *mIUserRepoMockGetUserByID {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("IUserRepoMock.GetUserByID mock is already set by Set")
	}

	if mmGetUserByID.defaultExpectation == nil {
		mmGetUserByID.defaultExpectation = &IUserRepoMockGetUserByIDExpectation{}
	}

	if mmGetUserByID.defaultExpectation.params != nil {
		mmGetUserByID.mock.t.Fatalf("IUserRepoMock.GetUserByID mock is already set by Expect")
	}

	if mmGetUserByID.defaultExpectation.paramPtrs == nil {
		mmGetUserByID.defaultExpectation.paramPtrs = &IUserRepoMockGetUserByIDParamPtrs{}
	}
	mmGetUserByID.defaultExpectation.paramPtrs.userID = &userID

	return mmGetUserByID
}

// Inspect accepts an inspector function that has same arguments as the iUserRepo.GetUserByID
func (mmGetUserByID *mIUserRepoMockGetUserByID) Inspect(f func(userID uuid.UUID)) *mIUserRepoMockGetUserByID {
	if mmGetUserByID.mock.inspectFuncGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("Inspect function is already set for IUserRepoMock.GetUserByID")
	}

	mmGetUserByID.mock.inspectFuncGetUserByID = f

	return mmGetUserByID
}

// Return sets up results that will be returned by iUserRepo.GetUserByID
func (mmGetUserByID *mIUserRepoMockGetUserByID) Return(up1 *domain.User, err error) *IUserRepoMock {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("IUserRepoMock.GetUserByID mock is already set by Set")
	}

	if mmGetUserByID.defaultExpectation == nil {
		mmGetUserByID.defaultExpectation = &IUserRepoMockGetUserByIDExpectation{mock: mmGetUserByID.mock}
	}
	mmGetUserByID.defaultExpectation.results = &IUserRepoMockGetUserByIDResults{up1, err}
	return mmGetUserByID.mock
}

// Set uses given function f to mock the iUserRepo.GetUserByID method
func (mmGetUserByID *mIUserRepoMockGetUserByID) Set(f func(userID uuid.UUID) (up1 *domain.User, err error)) *IUserRepoMock {
	if mmGetUserByID.defaultExpectation != nil {
		mmGetUserByID.mock.t.Fatalf("Default expectation is already set for the iUserRepo.GetUserByID method")
	}

	if len(mmGetUserByID.expectations) > 0 {
		mmGetUserByID.mock.t.Fatalf("Some expectations are already set for the iUserRepo.GetUserByID method")
	}

	mmGetUserByID.mock.funcGetUserByID = f
	return mmGetUserByID.mock
}

// When sets expectation for the iUserRepo.GetUserByID which will trigger the result defined by the following
// Then helper
func (mmGetUserByID *mIUserRepoMockGetUserByID) When(userID uuid.UUID) *IUserRepoMockGetUserByIDExpectation {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("IUserRepoMock.GetUserByID mock is already set by Set")
	}

	expectation := &IUserRepoMockGetUserByIDExpectation{
		mock:   mmGetUserByID.mock,
		params: &IUserRepoMockGetUserByIDParams{userID},
	}
	mmGetUserByID.expectations = append(mmGetUserByID.expectations, expectation)
	return expectation
}

// Then sets up iUserRepo.GetUserByID return parameters for the expectation previously defined by the When method
func (e *IUserRepoMockGetUserByIDExpectation) Then(up1 *domain.User, err error) *IUserRepoMock {
	e.results = &IUserRepoMockGetUserByIDResults{up1, err}
	return e.mock
}

// Times sets number of times iUserRepo.GetUserByID should be invoked
func (mmGetUserByID *mIUserRepoMockGetUserByID) Times(n uint64) *mIUserRepoMockGetUserByID {
	if n == 0 {
		mmGetUserByID.mock.t.Fatalf("Times of IUserRepoMock.GetUserByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserByID.expectedInvocations, n)
	return mmGetUserByID
}

func (mmGetUserByID *mIUserRepoMockGetUserByID) invocationsDone() bool {
	if len(mmGetUserByID.expectations) == 0 && mmGetUserByID.defaultExpectation == nil && mmGetUserByID.mock.funcGetUserByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserByID.mock.afterGetUserByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserByID implements activatehabit.iUserRepo
func (mmGetUserByID *IUserRepoMock) GetUserByID(userID uuid.UUID) (up1 *domain.User, err error) {
	mm_atomic.AddUint64(&mmGetUserByID.beforeGetUserByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserByID.afterGetUserByIDCounter, 1)

	if mmGetUserByID.inspectFuncGetUserByID != nil {
		mmGetUserByID.inspectFuncGetUserByID(userID)
	}

	mm_params := IUserRepoMockGetUserByIDParams{userID}

	// Record call args
	mmGetUserByID.GetUserByIDMock.mutex.Lock()
	mmGetUserByID.GetUserByIDMock.callArgs = append(mmGetUserByID.GetUserByIDMock.callArgs, &mm_params)
	mmGetUserByID.GetUserByIDMock.mutex.Unlock()

	for _, e := range mmGetUserByID.GetUserByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetUserByID.GetUserByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserByID.GetUserByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserByID.GetUserByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserByID.GetUserByIDMock.defaultExpectation.paramPtrs

		mm_got := IUserRepoMockGetUserByIDParams{userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetUserByID.t.Errorf("IUserRepoMock.GetUserByID got unexpected parameter userID, want: %#v, got: %#v%s\n", *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserByID.t.Errorf("IUserRepoMock.GetUserByID got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserByID.GetUserByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserByID.t.Fatal("No results are set for the IUserRepoMock.GetUserByID")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetUserByID.funcGetUserByID != nil {
		return mmGetUserByID.funcGetUserByID(userID)
	}
	mmGetUserByID.t.Fatalf("Unexpected call to IUserRepoMock.GetUserByID. %v", userID)
	return
}

// GetUserByIDAfterCounter returns a count of finished IUserRepoMock.GetUserByID invocations
func (mmGetUserByID *IUserRepoMock) GetUserByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByID.afterGetUserByIDCounter)
}

// GetUserByIDBeforeCounter returns a count of IUserRepoMock.GetUserByID invocations
func (mmGetUserByID *IUserRepoMock) GetUserByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByID.beforeGetUserByIDCounter)
}

// Calls returns a list of arguments used in each call to IUserRepoMock.GetUserByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserByID *mIUserRepoMockGetUserByID) Calls() []*IUserRepoMockGetUserByIDParams {
	mmGetUserByID.mutex.RLock()

	argCopy := make([]*IUserRepoMockGetUserByIDParams, len(mmGetUserByID.callArgs))
	copy(argCopy, mmGetUserByID.callArgs)

	mmGetUserByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserByIDDone returns true if the count of the GetUserByID invocations corresponds
// the number of defined expectations
func (m *IUserRepoMock) MinimockGetUserByIDDone() bool {
	if m.GetUserByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserByIDMock.invocationsDone()
}

// MinimockGetUserByIDInspect logs each unmet expectation
func (m *IUserRepoMock) MinimockGetUserByIDInspect() {
	for _, e := range m.GetUserByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IUserRepoMock.GetUserByID with params: %#v", *e.params)
		}
	}

	afterGetUserByIDCounter := mm_atomic.LoadUint64(&m.afterGetUserByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserByIDMock.defaultExpectation != nil && afterGetUserByIDCounter < 1 {
		if m.GetUserByIDMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IUserRepoMock.GetUserByID")
		} else {
			m.t.Errorf("Expected call to IUserRepoMock.GetUserByID with params: %#v", *m.GetUserByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserByID != nil && afterGetUserByIDCounter < 1 {
		m.t.Error("Expected call to IUserRepoMock.GetUserByID")
	}

	if !m.GetUserByIDMock.invocationsDone() && afterGetUserByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to IUserRepoMock.GetUserByID but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserByIDMock.expectedInvocations), afterGetUserByIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IUserRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockActivateHabitInspect()

			m.MinimockGetUserByIDInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IUserRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IUserRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockActivateHabitDone() &&
		m.MinimockGetUserByIDDone()
}
