// Code generated by http://github.com/gojuno/minimock (v3.3.11). DO NOT EDIT.

package createUser

import (
	"context"
	"main/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// IEventRouterMock implements createuser.iEventRouter
type IEventRouterMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcRouteAllEvents          func(ctx context.Context, events []domain.Event) (err error)
	inspectFuncRouteAllEvents   func(ctx context.Context, events []domain.Event)
	afterRouteAllEventsCounter  uint64
	beforeRouteAllEventsCounter uint64
	RouteAllEventsMock          mIEventRouterMockRouteAllEvents
}

// NewIEventRouterMock returns a mock for createuser.iEventRouter
func NewIEventRouterMock(t minimock.Tester) *IEventRouterMock {
	m := &IEventRouterMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RouteAllEventsMock = mIEventRouterMockRouteAllEvents{mock: m}
	m.RouteAllEventsMock.callArgs = []*IEventRouterMockRouteAllEventsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIEventRouterMockRouteAllEvents struct {
	optional           bool
	mock               *IEventRouterMock
	defaultExpectation *IEventRouterMockRouteAllEventsExpectation
	expectations       []*IEventRouterMockRouteAllEventsExpectation

	callArgs []*IEventRouterMockRouteAllEventsParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// IEventRouterMockRouteAllEventsExpectation specifies expectation struct of the iEventRouter.RouteAllEvents
type IEventRouterMockRouteAllEventsExpectation struct {
	mock      *IEventRouterMock
	params    *IEventRouterMockRouteAllEventsParams
	paramPtrs *IEventRouterMockRouteAllEventsParamPtrs
	results   *IEventRouterMockRouteAllEventsResults
	Counter   uint64
}

// IEventRouterMockRouteAllEventsParams contains parameters of the iEventRouter.RouteAllEvents
type IEventRouterMockRouteAllEventsParams struct {
	ctx    context.Context
	events []domain.Event
}

// IEventRouterMockRouteAllEventsParamPtrs contains pointers to parameters of the iEventRouter.RouteAllEvents
type IEventRouterMockRouteAllEventsParamPtrs struct {
	ctx    *context.Context
	events *[]domain.Event
}

// IEventRouterMockRouteAllEventsResults contains results of the iEventRouter.RouteAllEvents
type IEventRouterMockRouteAllEventsResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) Optional() *mIEventRouterMockRouteAllEvents {
	mmRouteAllEvents.optional = true
	return mmRouteAllEvents
}

// Expect sets up expected params for iEventRouter.RouteAllEvents
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) Expect(ctx context.Context, events []domain.Event) *mIEventRouterMockRouteAllEvents {
	if mmRouteAllEvents.mock.funcRouteAllEvents != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by Set")
	}

	if mmRouteAllEvents.defaultExpectation == nil {
		mmRouteAllEvents.defaultExpectation = &IEventRouterMockRouteAllEventsExpectation{}
	}

	if mmRouteAllEvents.defaultExpectation.paramPtrs != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by ExpectParams functions")
	}

	mmRouteAllEvents.defaultExpectation.params = &IEventRouterMockRouteAllEventsParams{ctx, events}
	for _, e := range mmRouteAllEvents.expectations {
		if minimock.Equal(e.params, mmRouteAllEvents.defaultExpectation.params) {
			mmRouteAllEvents.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRouteAllEvents.defaultExpectation.params)
		}
	}

	return mmRouteAllEvents
}

// ExpectCtxParam1 sets up expected param ctx for iEventRouter.RouteAllEvents
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) ExpectCtxParam1(ctx context.Context) *mIEventRouterMockRouteAllEvents {
	if mmRouteAllEvents.mock.funcRouteAllEvents != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by Set")
	}

	if mmRouteAllEvents.defaultExpectation == nil {
		mmRouteAllEvents.defaultExpectation = &IEventRouterMockRouteAllEventsExpectation{}
	}

	if mmRouteAllEvents.defaultExpectation.params != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by Expect")
	}

	if mmRouteAllEvents.defaultExpectation.paramPtrs == nil {
		mmRouteAllEvents.defaultExpectation.paramPtrs = &IEventRouterMockRouteAllEventsParamPtrs{}
	}
	mmRouteAllEvents.defaultExpectation.paramPtrs.ctx = &ctx

	return mmRouteAllEvents
}

// ExpectEventsParam2 sets up expected param events for iEventRouter.RouteAllEvents
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) ExpectEventsParam2(events []domain.Event) *mIEventRouterMockRouteAllEvents {
	if mmRouteAllEvents.mock.funcRouteAllEvents != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by Set")
	}

	if mmRouteAllEvents.defaultExpectation == nil {
		mmRouteAllEvents.defaultExpectation = &IEventRouterMockRouteAllEventsExpectation{}
	}

	if mmRouteAllEvents.defaultExpectation.params != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by Expect")
	}

	if mmRouteAllEvents.defaultExpectation.paramPtrs == nil {
		mmRouteAllEvents.defaultExpectation.paramPtrs = &IEventRouterMockRouteAllEventsParamPtrs{}
	}
	mmRouteAllEvents.defaultExpectation.paramPtrs.events = &events

	return mmRouteAllEvents
}

// Inspect accepts an inspector function that has same arguments as the iEventRouter.RouteAllEvents
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) Inspect(f func(ctx context.Context, events []domain.Event)) *mIEventRouterMockRouteAllEvents {
	if mmRouteAllEvents.mock.inspectFuncRouteAllEvents != nil {
		mmRouteAllEvents.mock.t.Fatalf("Inspect function is already set for IEventRouterMock.RouteAllEvents")
	}

	mmRouteAllEvents.mock.inspectFuncRouteAllEvents = f

	return mmRouteAllEvents
}

// Return sets up results that will be returned by iEventRouter.RouteAllEvents
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) Return(err error) *IEventRouterMock {
	if mmRouteAllEvents.mock.funcRouteAllEvents != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by Set")
	}

	if mmRouteAllEvents.defaultExpectation == nil {
		mmRouteAllEvents.defaultExpectation = &IEventRouterMockRouteAllEventsExpectation{mock: mmRouteAllEvents.mock}
	}
	mmRouteAllEvents.defaultExpectation.results = &IEventRouterMockRouteAllEventsResults{err}
	return mmRouteAllEvents.mock
}

// Set uses given function f to mock the iEventRouter.RouteAllEvents method
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) Set(f func(ctx context.Context, events []domain.Event) (err error)) *IEventRouterMock {
	if mmRouteAllEvents.defaultExpectation != nil {
		mmRouteAllEvents.mock.t.Fatalf("Default expectation is already set for the iEventRouter.RouteAllEvents method")
	}

	if len(mmRouteAllEvents.expectations) > 0 {
		mmRouteAllEvents.mock.t.Fatalf("Some expectations are already set for the iEventRouter.RouteAllEvents method")
	}

	mmRouteAllEvents.mock.funcRouteAllEvents = f
	return mmRouteAllEvents.mock
}

// When sets expectation for the iEventRouter.RouteAllEvents which will trigger the result defined by the following
// Then helper
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) When(ctx context.Context, events []domain.Event) *IEventRouterMockRouteAllEventsExpectation {
	if mmRouteAllEvents.mock.funcRouteAllEvents != nil {
		mmRouteAllEvents.mock.t.Fatalf("IEventRouterMock.RouteAllEvents mock is already set by Set")
	}

	expectation := &IEventRouterMockRouteAllEventsExpectation{
		mock:   mmRouteAllEvents.mock,
		params: &IEventRouterMockRouteAllEventsParams{ctx, events},
	}
	mmRouteAllEvents.expectations = append(mmRouteAllEvents.expectations, expectation)
	return expectation
}

// Then sets up iEventRouter.RouteAllEvents return parameters for the expectation previously defined by the When method
func (e *IEventRouterMockRouteAllEventsExpectation) Then(err error) *IEventRouterMock {
	e.results = &IEventRouterMockRouteAllEventsResults{err}
	return e.mock
}

// Times sets number of times iEventRouter.RouteAllEvents should be invoked
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) Times(n uint64) *mIEventRouterMockRouteAllEvents {
	if n == 0 {
		mmRouteAllEvents.mock.t.Fatalf("Times of IEventRouterMock.RouteAllEvents mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRouteAllEvents.expectedInvocations, n)
	return mmRouteAllEvents
}

func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) invocationsDone() bool {
	if len(mmRouteAllEvents.expectations) == 0 && mmRouteAllEvents.defaultExpectation == nil && mmRouteAllEvents.mock.funcRouteAllEvents == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRouteAllEvents.mock.afterRouteAllEventsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRouteAllEvents.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RouteAllEvents implements createuser.iEventRouter
func (mmRouteAllEvents *IEventRouterMock) RouteAllEvents(ctx context.Context, events []domain.Event) (err error) {
	mm_atomic.AddUint64(&mmRouteAllEvents.beforeRouteAllEventsCounter, 1)
	defer mm_atomic.AddUint64(&mmRouteAllEvents.afterRouteAllEventsCounter, 1)

	if mmRouteAllEvents.inspectFuncRouteAllEvents != nil {
		mmRouteAllEvents.inspectFuncRouteAllEvents(ctx, events)
	}

	mm_params := IEventRouterMockRouteAllEventsParams{ctx, events}

	// Record call args
	mmRouteAllEvents.RouteAllEventsMock.mutex.Lock()
	mmRouteAllEvents.RouteAllEventsMock.callArgs = append(mmRouteAllEvents.RouteAllEventsMock.callArgs, &mm_params)
	mmRouteAllEvents.RouteAllEventsMock.mutex.Unlock()

	for _, e := range mmRouteAllEvents.RouteAllEventsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRouteAllEvents.RouteAllEventsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRouteAllEvents.RouteAllEventsMock.defaultExpectation.Counter, 1)
		mm_want := mmRouteAllEvents.RouteAllEventsMock.defaultExpectation.params
		mm_want_ptrs := mmRouteAllEvents.RouteAllEventsMock.defaultExpectation.paramPtrs

		mm_got := IEventRouterMockRouteAllEventsParams{ctx, events}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRouteAllEvents.t.Errorf("IEventRouterMock.RouteAllEvents got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.events != nil && !minimock.Equal(*mm_want_ptrs.events, mm_got.events) {
				mmRouteAllEvents.t.Errorf("IEventRouterMock.RouteAllEvents got unexpected parameter events, want: %#v, got: %#v%s\n", *mm_want_ptrs.events, mm_got.events, minimock.Diff(*mm_want_ptrs.events, mm_got.events))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRouteAllEvents.t.Errorf("IEventRouterMock.RouteAllEvents got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRouteAllEvents.RouteAllEventsMock.defaultExpectation.results
		if mm_results == nil {
			mmRouteAllEvents.t.Fatal("No results are set for the IEventRouterMock.RouteAllEvents")
		}
		return (*mm_results).err
	}
	if mmRouteAllEvents.funcRouteAllEvents != nil {
		return mmRouteAllEvents.funcRouteAllEvents(ctx, events)
	}
	mmRouteAllEvents.t.Fatalf("Unexpected call to IEventRouterMock.RouteAllEvents. %v %v", ctx, events)
	return
}

// RouteAllEventsAfterCounter returns a count of finished IEventRouterMock.RouteAllEvents invocations
func (mmRouteAllEvents *IEventRouterMock) RouteAllEventsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRouteAllEvents.afterRouteAllEventsCounter)
}

// RouteAllEventsBeforeCounter returns a count of IEventRouterMock.RouteAllEvents invocations
func (mmRouteAllEvents *IEventRouterMock) RouteAllEventsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRouteAllEvents.beforeRouteAllEventsCounter)
}

// Calls returns a list of arguments used in each call to IEventRouterMock.RouteAllEvents.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRouteAllEvents *mIEventRouterMockRouteAllEvents) Calls() []*IEventRouterMockRouteAllEventsParams {
	mmRouteAllEvents.mutex.RLock()

	argCopy := make([]*IEventRouterMockRouteAllEventsParams, len(mmRouteAllEvents.callArgs))
	copy(argCopy, mmRouteAllEvents.callArgs)

	mmRouteAllEvents.mutex.RUnlock()

	return argCopy
}

// MinimockRouteAllEventsDone returns true if the count of the RouteAllEvents invocations corresponds
// the number of defined expectations
func (m *IEventRouterMock) MinimockRouteAllEventsDone() bool {
	if m.RouteAllEventsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RouteAllEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RouteAllEventsMock.invocationsDone()
}

// MinimockRouteAllEventsInspect logs each unmet expectation
func (m *IEventRouterMock) MinimockRouteAllEventsInspect() {
	for _, e := range m.RouteAllEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IEventRouterMock.RouteAllEvents with params: %#v", *e.params)
		}
	}

	afterRouteAllEventsCounter := mm_atomic.LoadUint64(&m.afterRouteAllEventsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RouteAllEventsMock.defaultExpectation != nil && afterRouteAllEventsCounter < 1 {
		if m.RouteAllEventsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IEventRouterMock.RouteAllEvents")
		} else {
			m.t.Errorf("Expected call to IEventRouterMock.RouteAllEvents with params: %#v", *m.RouteAllEventsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRouteAllEvents != nil && afterRouteAllEventsCounter < 1 {
		m.t.Error("Expected call to IEventRouterMock.RouteAllEvents")
	}

	if !m.RouteAllEventsMock.invocationsDone() && afterRouteAllEventsCounter > 0 {
		m.t.Errorf("Expected %d calls to IEventRouterMock.RouteAllEvents but found %d calls",
			mm_atomic.LoadUint64(&m.RouteAllEventsMock.expectedInvocations), afterRouteAllEventsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IEventRouterMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockRouteAllEventsInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IEventRouterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IEventRouterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRouteAllEventsDone()
}
