app_name: "bot-service"
env: "local"
port: 8080

db:
  connection: "postgres://postgres:postgres@localhost:6432/postgres"
  dbName: "postgres"
  user_name: "postgres"
  timeout: 3s
graceful_timeout: 10s
scrape_interval: 5s
logger:
  add_source: true
  level: -4 #debug
kafka:
  host: localhost
  port: 6502
