app_name: "bot-service"
env: "local"
port: 8080

db:
  connection: "postgres://postgres:postgres@localhost:6432/postgres"
  dbName: "postgres"
  user_name: "postgres"
  timeout: 3s
graceful_timeout: 10s
scrape_interval: 5s
logger:
  add_source: true
  level: -4 #debug
kafka:
  host:
    - localhost:6502
user_event_producer_config:
  topic: user_created
  required_acks: -1
  compression_codec: 1
  retry:
    max: 5
    backoff: 30ms
  request_timeout: 100ms
  idempotent: true
  return_successes: true
  max_in_flight_requests_per_connection: 1