app_name: "bot-service"
env: "prod"

db:
  connection: "postgres://postgres:postgres@bot-service-pgbouncer:6432/postgres"
  dbName: "postgres"
  user_name: "postgres"
  timeout: 3s
graceful_timeout: 30s
bot:
  token: 'PROD_TOKEN'
  poller_timeout: 10s
